import React from 'react'
import './style.css'
import {InputGroup, Form, Col, Button, Table, FormControl} from 'react-bootstrap';


function Notifications() {
    return (
        <div className="contents">
            <div className="topmenu">   
                <Form>
                    <Form.Row>
                    <Form.Group as={Col} md="3" controlId="formGridState">
                    <Form.Label>Notification Title</Form.Label>
                        <InputGroup className="mb-3">
                            <FormControl
                                placeholder="Search Notification ....."
                                aria-label="Notification title"
                                aria-describedby="basic-addon2"
                            />
                            <InputGroup.Append>
                                <Button variant="outline-primary">Search</Button>
                            </InputGroup.Append>
                        </InputGroup>
                    </Form.Group>

                    </Form.Row>
                </Form>
            </div>
            <div className="tablediv">
            <Table striped bordered hover>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Notification Title</th>
                        <th>Catagory</th>
                        <th>Date Generated</th>
                        <th>Generated By</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Notification1</td>
                        <td>Quotation Announced</td>
                        <td>15/4/2019</td>
                        <td>Health Department</td>
                        <td><a href="#">View</a></td>
                    </tr>
                </tbody>
                </Table>
            </div>            
        </div>
    )
}

export default Notifications;